steps:

- name: 'gcr.io/cloud-builders/docker'
  id: Build docker image - SHORT_SHA
  args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ART_REGISTRY}/${_IMAGE}:$SHORT_SHA', '.' ]


- name: 'gcr.io/cloud-builders/docker'
  id: Build docker image - latest
  args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ART_REGISTRY}/${_IMAGE}:latest', '.' ]

- id: test
  name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud beta container binauthz attestations sign-and-create \
      --project='$PROJECT_ID' \
      --artifact-url='${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ART_REGISTRY}/${_IMAGE}:latest' \
      --attestor='projects/${PROJECT_ID}/attestors/built-by-cloud-build' \
      --attestor-project='$PROJECT_ID' \
      --keyversion-project='verified-builder' \
      --keyversion-location='${_REGION}' \
      --keyversion-keyring='attestor' \
      --keyversion-key='builtByGCB' \
      --keyversion='1'

- name: 'gcr.io/cloud-builders/docker'
  id: Push docker image with SHA tag
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ART_REGISTRY}/${_IMAGE}:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: Push docker image with latest tag
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ART_REGISTRY}/${_IMAGE}:latest']

# hack
- name: 'google/cloud-sdk:latest'
  id: inject sha
  entrypoint: 'sh'
  args:
  - |
    sed -i "s/my-app:latest/my-app:${SHORT_SHA}/g" k8.yaml

- name: 'google/cloud-sdk:latest'
  id: Trigger Cloud Deploy
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region ${_REGION}
    gcloud deploy apply --file clouddeploy-pipeline.yaml
    gcloud deploy releases create ${_IMAGE}-$SHORT_SHA \
                        --delivery-pipeline=my-app-pipeline \
                        --skaffold-file=skaffold.yaml

options:
    requestedVerifyOption: VERIFIED